function [intersection] = nodeintersection(tree, index1,index2)
%CUBEINTERSECTION Compute if node at index 1 is inside
% or next to node at index 2
%Inputs:
%   tree   : tree structure generated by Octree
%   index1 : node 1 which we want to check against
%   index2 : (1,n) or (n,1) array of indices which we want check are next 
%            to node 1
%
%Output:
%   intersection : (1,n) or (n,1) Logical array determining if index 2 is 
%                  next to index 1            

coord1 = tree.binCorners(index1,:);
coord2 = tree.binCorners(index2,:);

intersection = not(any([coord2(:,1) > coord1(4),...
                        coord2(:,4) < coord1(1),...
                        coord2(:,2) > coord1(5),...
                        coord2(:,5) < coord1(2),...
                        coord2(:,3) > coord1(6),...
                        coord2(:,6) < coord1(3)],2));
end

