function [order] = postordertree(tree,index)
% PreOrderTree  Compute the post order tree traversal
% Compute the downward traversal of the tree from root to leaf nodes
%Inputs:
%   tree  : tree structure generated by Octree
%   index : root of tree structure
%
%Output:
%   order : row vector with traversal order

order = [];
if isleaf(tree,index)==0
    children = tree.binChildren(index,:);
    for i = 1:8
        order = [order postordertree(tree,children(i))];
    end
    order = [order index];
else
    order = index;
end
end
