function [order] = preordertree(tree,index)
% PreOrderTree  Compute the pre order tree traversal
% Compute the upwards traversal of the tree from leaf nodes to root
%Inputs:
%   tree  : tree structure generated by Octree
%   index : root of tree structure
%
%Output:
%   order : row vector with traversal order

order = index;
if isleaf(tree,index)==0
    children = tree.binChildren(index,:);
    for i = 1:8
        order = [order preordertree(tree,children(i))];
    end
    
else
    order = index;
end
end
