function [isLeaf] = isleaf(tree,index,type)
%isLeaf  Checks if the node is a leaf
%Inputs:
%   tree   : tree structure generated by Octree
%   index1 : (1,n) or (n,1) index of node
%   type   : 'Target' or 'Potential' or 'All', type of point to check for
%
%Output:
%   isLeaf : (1,n) or (n,1) Logical array determining if node is a leaf
%            node

switch type
    case 'Target'
        isLeaf = ismember(index,tree.pointIndex(tree.targets));
    case 'Potential'
        isLeaf = ismember(index,tree.pointIndex(tree.potentials));
    case 'All'
        children = tree.nodeChildren(index,:);
        isLeaf = (children(:,1) == 0);
    otherwise
        warning('Point type not specified correctly in isLeaf.')
end
end

