function [isLeaf] = isleaf(tree, index)
%isLeaf  Checks if the node is a leaf
%Inputs:
%   tree   : tree structure generated by Octree
%   index1 : (1,n) or (n,1) index of node
%
%Output:
%   isLeaf : (1,n) or (n,1) Logical array determining if node is a leaf
%            node

children = tree.nodeChildren(index,:);
isLeaf = (children(:,1) == 0);
end

